const hotels = [
    // VILLA CATEGORY
    {
      "id": 1,
      "name": "Luxury Ocean Villa",
      "location": "Maldives",
      "latitude": 3.2028,
      "longitude": 73.2207,
      "category": "villa",
      "originalPrice": 50000,
      "discountedPrice": 45000,
      "discountPercentage": 10,
      "currency": "INR",
      "totalPrice": 90000,
      "amenities": ["Spa", "Lounge area", "Airport transfer", "Pool", "Free WiFi"],
      "image": "https://plus.unsplash.com/premium_photo-1682377521753-58d1fd9fa5ce?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bHV4dXJ5JTIwdmlsbGF8ZW58MHx8MHx8fDA%3D"
      
      },
      {
        "id": 2,
        "name": "Hillside Retreat Villa",
        "location": "Switzerland",
        "latitude": 46.8182,
        "longitude": 8.2275,
        "category": "villa",
        "originalPrice": 35000,
        "discountedPrice": 32000,
        "discountPercentage": 8,
        "currency": "INR",
        "totalPrice": 64000,
        "amenities": ["Free breakfast", "Non-smoking", "Pool", "24/7 front desk"],
        "image": "https://media.istockphoto.com/id/503044702/photo/illuminated-sky-and-outside-of-waterfront-buiding.jpg?s=612x612&w=0&k=20&c=xkDBkqmCVvhR4idfybXRb-yFS0KqOjqtikg_LtO4pzs="
      },
      {
        "id": 3,
        "name": "Secluded Beach Villa",
        "location": "Bali, Indonesia",
        "latitude": -8.3405,
        "longitude": 115.0920,
        "category": "villa",
        "originalPrice": 30000,
        "discountedPrice": 28000,
        "discountPercentage": 7,
        "currency": "INR",
        "totalPrice": 56000,
        "amenities": ["Airport transfer", "Free WiFi", "Single bed", "24/7 front desk"],
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/464666146.jpg?k=b8ec6760985989a0c688f56678a3ac2613300ebb000d13a63d7bbddba913633c&o=&hp=1"
      },
      {
        "id": 4,
        "name": "Tropical Garden Villa",
        "location": "Thailand",
        "latitude": 15.8700,
        "longitude": 100.9925,
        "category": "villa",
        "originalPrice": 18000,
        "discountedPrice": 15000,
        "discountPercentage": 15,
        "currency": "INR",
        "totalPrice": 30000,
        "amenities": ["Non-smoking", "Double bed", "Pool", "Free breakfast"],
        "image": "https://t4.ftcdn.net/jpg/03/70/64/43/360_F_370644357_MDF4UXLAXTyyi2OyuK66tWW9cA2f8svL.jpg"
      },
    
      // HOSTELS CATEGORY
      {
        "id": 6,
        "name": "City View Hostel",
        "location": "New York, USA",
        "latitude": 40.7128,
        "longitude": -74.0060,
        "category": "Hostels",
        "originalPrice": 6000,
        "discountedPrice": 5000,
        "discountPercentage": 16,
        "currency": "INR",
        "totalPrice": 10000,
        "amenities": ["Free WiFi", "Single bed", "Non-smoking", "Free breakfast"],
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIVm8tfnV_RzT-0Ep7duqNTS5qyO_B5tgbKgt7H2EPytT1QX5sGONFNvCjTRWo51zoh5Y&usqp=CAU"
      },
      {
        "id": 7,
        "name": "Backpacker’s Paradise",
        "location": "Bangkok, Thailand",
        "latitude": 13.7563,
        "longitude": 100.5018,
        "category": "Hostels",
        "originalPrice": 5000,
        "discountedPrice": 4000,
        "discountPercentage": 20,
        "currency": "INR",
        "totalPrice": 8000,
        "amenities": ["Double bed", "24/7 front desk", "Airport transfer", "Pool"],
        "image": "https://media.istockphoto.com/id/1292522563/photo/modern-college-dorm-room-with-messy-bunk-beds-and-parquet-floor.jpg?s=612x612&w=0&k=20&c=Kq36voIf8cmnQaGv0Q1UdPf3Ty5mOpHdjoFj8Ly4Phw="
      },
    
      // RESORT CATEGORY
      {
        "id": 11,
        "name": "Desert Safari Resort",
        "location": "Dubai, UAE",
        "latitude": 25.276987,
        "longitude": 55.296249,
        "category": "Resort",
        "originalPrice": 25000,
        "discountedPrice": 22000,
        "discountPercentage": 12,
        "currency": "INR",
        "totalPrice": 44000,
        "amenities": ["Desert tours", "Spa", "Free breakfast", "Airport transfer"],
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT--0dTGyY6FD0Iwi3W5f24UxcILrtDhEt5RHS9x8Feu9og4fkFSlyUznHVJO8Crn3P3pU&usqp=CAU"
      },
      {
        "id": 12,
        "name": "Snowy Mountain Resort",
        "location": "Switzerland",
        "latitude": 46.8182,
        "longitude": 8.2275,
        "category": "Resort",
        "originalPrice": 30000,
        "discountedPrice": 27000,
        "discountPercentage": 10,
        "currency": "INR",
        "totalPrice": 54000,
        "amenities": ["Skiing", "Hot tub", "24/7 front desk", "Non-smoking"],
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp3ydqG0Mqs5kQuS-d73LpVRTEbqafoWYBIlr6uhbqSoq1JI6mDr9E2k9wG6napH_SVZs&usqp=CAU"
      },
    
      // HOUSEBOAT CATEGORY
      {
        "id": 16,
        "name": "Backwater Houseboat",
        "location": "Kerala, India",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "category": "Houseboat",
        "originalPrice": 25000,
        "discountedPrice": 23000,
        "discountPercentage": 8,
        "currency": "INR",
        "totalPrice": 46000,
        "amenities": ["Shore excursions", "Free breakfast", "Air conditioning", "Fishing"],
        "image": "https://w0.peakpx.com/wallpaper/22/340/HD-wallpaper-houseboat-rest-shore-vacation-relax-trees-palms-palm-trees-boat-water-trip-summer-nature-river.jpg"
      },
      {
        "id": 17,
        "name": "Alleppey Houseboat",
        "location": "Kerala, India",
        "latitude": 9.5000,
        "longitude": 76.3388,
        "category": "Houseboat",
        "originalPrice": 27000,
        "discountedPrice": 25000,
        "discountPercentage": 10,
        "currency": "INR",
        "totalPrice": 50000,
        "amenities": ["Shore excursions", "Spa", "24/7 front desk"],
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWR1NiOlDSsTRCcVgZinn7iImwe8Gj3oqiyg&s"
      },
      {
        "id": 18,
        "name": "Luxury Houseboat",
        "location": "Cochin, India",
        "latitude": 9.9312,
        "longitude": 76.2588,
        "category": "Houseboat",
        "originalPrice": 22000,
        "discountedPrice": 21000,
        "discountPercentage": 5,
        "currency": "INR",
        "totalPrice": 42000,
        "amenities": ["Shore excursions", "Free WiFi", "Fishing", "Non-smoking"],
        "image": "https://media.istockphoto.com/id/1266651692/photo/houseboat-in-alappuzha-backwaters-kerala.jpg?s=612x612&w=0&k=20&c=G432lmdUz9qrW6D4sZYxLe6K-Km85OEmZg0qpcGyRCI="
      },
      {
        "id": 19,
        "name": "Sunset Houseboat",
        "location": "Kumarakom, India",
        "latitude": 9.5915,
        "longitude": 76.5232,
        "category": "Houseboat",
        "originalPrice": 28000,
        "discountedPrice": 26000,
        "discountPercentage": 7,
        "currency": "INR",
        "totalPrice": 52000,
        "amenities": ["Shore excursions", "Free breakfast", "Spa", "Fishing"],
        "image": "https://images.pexels.com/photos/962464/pexels-photo-962464.jpeg?cs=srgb&dl=pexels-godson-bright-352845-962464.jpg&fm=jpg"
      },
    
      // INDIAN RESORT CATEGORY (Added more Indian resorts)
      {
        "id": 20,
        "name": "Goa Beach Resort",
        "location": "Goa, India",
        "latitude": 15.2993,
        "longitude": 74.124,
        "category": "Resort",
        "originalPrice": 20000,
        "discountedPrice": 18000,
        "discountPercentage": 10,
        "currency": "INR",
        "totalPrice": 36000,
        "amenities": ["Beach view", "Free breakfast", "Spa", "Swimming pool"],
        "image": "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?cs=srgb&dl=pexels-thorsten-technoman-109353-338504.jpg&fm=jpg"
      },
      {
        "id": 21,
        "name": "Kerala Ayurvedic Resort",
        "location": "Kerala, India",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "category": "Resort",
        "originalPrice": 22000,
        "discountedPrice": 20000,
        "discountPercentage": 9,
        "currency": "INR",
        "totalPrice": 40000,
        "amenities": ["Ayurvedic treatments", "Spa", "Free breakfast", "Yoga sessions"],
        "image": "https://c4.wallpaperflare.com/wallpaper/787/399/647/life-resort-travel-vacation-wallpaper-preview.jpg"
      },
    
      // ALL INCLUSIVE CATEGORY (includes all categories)
      {
        "id": 100,
        "name": "All-Inclusive Resort",
        "location": "India",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "category": "All Inclusive",
        "originalPrice": 35000,
        "discountedPrice": 30000,
        "discountPercentage": 14,
        "currency": "INR",
        "totalPrice": 60000,
        "amenities": ["Spa", "Free breakfast", "All meals included", "Pool", "Yoga sessions", "Fishing", "Skiing", "Airport transfer"],
        "image": "https://source.unsplash.com/400x300/?all-inclusive,india"
      },
      
      
        {
          "id": 101,
          "name": "Mumbai Grand Hotel",
          "location": "Mumbai, India",
          "latitude": 19.0760,
          "longitude": 72.8777,
          "category": "mumbai",
          "originalPrice": 25000,
          "discountedPrice": 22000,
          "discountPercentage": 12,
          "currency": "INR",
          "totalPrice": 44000,
          "amenities": ["Infinity Pool", "Sea View", "Spa", "Fine Dining"],
          "image": "https://media-cdn.tripadvisor.com/media/photo-s/26/6e/23/ac/grand-hotel-mumbai.jpg"
        },
        {
          "id": 102,
          "name": "mumbai Beach Resort",
          "location": "mumbai, India",
          "latitude": 19.0912,
          "longitude": 72.8274,
          "category": "mumbai",
          "originalPrice": 18000,
          "discountedPrice": 16000,
          "discountPercentage": 11,
          "currency": "INR",
          "totalPrice": 32000,
          "amenities": ["Beach Access", "Pool", "Spa", "Free Breakfast"],
          "image": "https://pix10.agoda.net/hotelImages/109194/-1/794d8c2e38fddc19ee8dd07ef7c2086a.jpg?ce=0&s=414x232&ar=16x9"
        },
        {
          "id": 103,
          "name": "Hotel Taj",
          "location": "Mumbai, India",
          "latitude": 19.0765,
          "longitude": 72.8500,
          "category": "mumbai",
          "originalPrice": 26000,
          "discountedPrice": 23000,
          "discountPercentage": 10,
          "currency": "INR",
          "totalPrice": 9000,
          "amenities": ["Free WiFi", "Breakfast", "Air Conditioning"],
          "image": "https://rukmini-ct.flixcart.com/q_75,w_420,h_300,fl_progressive,e_sharpen:80,c_fill,dpr_2,f_auto/ct-hotel-images/places/hotels/cms/2596/259671/images/image_259671_021388d6-f0fe-4e78-ac38-2d0b62a868a4_proc.jpeg"
        },
        {
          id: 501,
          name: "Taj Coromandel",
          location: "Chennai, India",
          latitude: 13.0631,
          longitude: 80.2515,
          category: "chennai",
          originalPrice: 14000,
          discountedPrice: 12500,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 25000,
          amenities: ["Luxury Suites", "Fine Dining", "Swimming Pool"],
          image: "https://static.businessworld.in/coromandel_20240515151720_ogImage_26.jpg"
        },
        {
          id: 502,
          name: "ITC Grand Chola",
          location: "Chennai, India",
          latitude: 13.0102,
          longitude: 80.2206,
          category: "chennai",
          originalPrice: 16000,
          discountedPrice: 14400,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 28800,
          amenities: ["5-Star Dining", "Luxury Spa", "Business Lounge"],
          image: "https://www.itchotels.com/content/dam/itchotels/in/umbrella/itc/hotels/itcgrandchola-chennai/images/overview/overview-desktop/exterior-dusk.png"
        },
        {
          id: 503,
          name: "The Leela Palace",
          location: "Chennai, India",
          latitude: 13.0023,
          longitude: 80.2668,
          category: "chennai",
          originalPrice: 18000,
          discountedPrice: 16200,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 32400,
          amenities: ["Ocean View", "Infinity Pool", "Executive Lounge"],
          image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/The_Leela_Palace_Chennai.jpg"
        },
        
      
        {
          id: 201,
          name: "DV Manor",
          location: "Vijayawada, India",
          latitude: 16.5062,
          longitude: 80.648,
          category: "vijayawada",
          originalPrice: 5000,
          discountedPrice: 4500,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 9000,
          amenities: ["Free WiFi", "Restaurant", "Parking"],
          image: "https://www.subahotels.com/images/hotels/26_Jun_2024_10_46_31Quality-Hotel-D-V-Manor,-Vijayawada.jpg"
        },
        {
          id: 202,
          name: "Novotel",
          location: "Vijayawada, India",
          latitude: 16.5143,
          longitude: 80.6324,
          category: "vijayawada",
          originalPrice: 6000,
          discountedPrice: 5200,
          discountPercentage: 13,
          currency: "INR",
          totalPrice: 10400,
          amenities: ["Air Conditioning", "Gym", "Room Service"],
          image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/2a/1a/b7/exterior.jpg?w=1200&h=-1&s=1"
        },
        {
          id: 569,
          name: "Gateway Vijayawada",
          location: "Vijayawada, India",
          latitude: 16.5214,
          longitude: 80.6397,
          category: "vijayawada",
          originalPrice: 7500,
          discountedPrice: 6800,
          discountPercentage: 9,
          currency: "INR",
          totalPrice: 13600,
          amenities: ["Swimming Pool", "Free Breakfast", "Spa"],
          image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/149878371.jpg?k=7b9ac4cbcf28e026bfa7a7771d2954ce4b675c3b8f1f61080d26757759f127e9&o=&hp=1"
        },
        {
          id: 301,
          name: "Dolphin Hotel",
          location: "Visakhapatnam, India",
          latitude: 17.6868,
          longitude: 83.2185,
          category: "visakhapatnam",
          originalPrice: 6500,
          discountedPrice: 5800,
          discountPercentage: 11,
          currency: "INR",
          totalPrice: 11600,
          amenities: ["Swimming Pool", "Gym", "Spa"],
          image: "https://content.skyscnr.com/available/1555466594/1555466594_WxH.jpg"
        },
        {
          id: 302,
          name: "Novotel Visakhapatnam",
          location: "Visakhapatnam, India",
          latitude: 17.7105,
          longitude: 83.3164,
          category: "visakhapatnam",
          originalPrice: 9000,
          discountedPrice: 8200,
          discountPercentage: 9,
          currency: "INR",
          totalPrice: 16400,
          amenities: ["Ocean View", "Free WiFi", "Business Center"],
          image: "https://live.staticflickr.com/2911/33251546200_8153db1d45_b.jpg"
        },
        {
          id: 303,
          name: "Bay View Resort",
          location: "Visakhapatnam, India",
          latitude: 17.7284,
          longitude: 83.3297,
          category: "visakhapatnam",
          originalPrice: 7800,
          discountedPrice: 7000,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 14000,
          amenities: ["Beach Access", "Free Breakfast", "Parking"],
          image: "https://bayviewhotelvizag.com/images/Gallery/bayview.jpg"
        },
        {
          id: 401,
          name: "The Imperial New Delhi",
          location: "Delhi, India",
          latitude: 28.6139,
          longitude: 77.209,
          category: "delhi",
          originalPrice: 15000,
          discountedPrice: 13500,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 27000,
          amenities: ["Luxury Suites", "Fine Dining", "Spa"],
          image: "https://www.andbeyond.com/wp-content/uploads/sites/5/Lobby-at-The-Imperial.jpg"
        },
        {
          id: 402,
          name: "Radisson Blu Plaza",
          location: "Delhi, India",
          latitude: 28.5623,
          longitude: 77.1209,
          category: "Delhi",
          originalPrice: 12000,
          discountedPrice: 10800,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 21600,
          amenities: ["Business Lounge", "Swimming Pool", "Fitness Center"],
          image: "https://media.radissonhotels.net/image/radisson-blu-plaza-hotel-delhi-airport/exterior/16256-114048-f89653467_4k.jpg?impolicy=HomeHero"
        },
        {
          id: 403,
          name: "ITC Maurya",
          location: "Delhi, India",
          latitude: 28.5952,
          longitude: 77.1734,
          category: "delhi",
          originalPrice: 18000,
          discountedPrice: 16200,
          discountPercentage: 10,
          currency: "INR",
          totalPrice: 32400,
          amenities: ["5-Star Dining", "Luxury Spa", "Executive Lounge"],
          image: "https://www.itchotels.com/content/dam/itchotels/in/umbrella/itc/hotels-listing/hotels-listing-card/itc-maratha.png"
        },
        
      
        {
          "id": 107,
          "name": "Bangkok Sky Hotel",
          "location": "Bangkok, Thailand",
          "latitude": 13.7563,
          "longitude": 100.5018,
          "category": "Bangkok",
          "originalPrice": 30000,
          "discountedPrice": 27000,
          "discountPercentage": 10,
          "currency": "THB",
          "totalPrice": 54000,
          "amenities": ["Sky Bar", "Infinity Pool", "Gym", "Luxury Dining"],
          "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/216005808.jpg?k=3365faed5ee94e38470f90a7d63c29eb69aaa4285d8c58b9bb6e8527055bf766&o=&hp=1"
        },
        {
          "id": 108,
          "name": "Bangkok Riverside Resort",
          "location": "Bangkok, Thailand",
          "latitude": 13.7367,
          "longitude": 100.5245,
          "category": "Bangkok",
          "originalPrice": 25000,
          "discountedPrice": 22000,
          "discountPercentage": 12,
          "currency": "THB",
          "totalPrice": 44000,
          "amenities": ["River View", "Spa", "Free Yoga", "Swimming Pool"],
          "image": "https://www.momondo.in/rimg/himg/ec/ab/55/revato-2978-12328637-536504.jpg?width=968&height=607&crop=true"
        },
        {
          "id": 109,
          "name": "Bangkok Backpackers Hostel",
          "location": "Bangkok, Thailand",
          "latitude": 13.7565,
          "longitude": 100.5039,
          "category": "Bangkok",
          "originalPrice": 4000,
          "discountedPrice": 3500,
          "discountPercentage": 12,
          "currency": "THB",
          "totalPrice": 7000,
          "amenities": ["Shared Kitchen", "WiFi", "Community Lounge"],
          "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/86462032.jpg?k=0e1adc11894d6ade9e94f0b42945c025e4248973c4c4f257f40c420908c69373&o=&hp=1"
        },
    ];
    
    
   
  export default hotels;